# This yaml is for ReadTheDocs to build the documentation for en and ja.
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    nodejs: "24"
  jobs:
    pre_create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    create_environment:
      - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    install:
      - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --frozen --no-default-groups --group dev
    post_install:
      - uv run python -m ipykernel install --user --name=qamomile  # Install the kernel for Jupyter
      - chmod +x ./docs/build.sh  # Enable execution of the build script
    build:
      html:
        - ./docs/build.sh build
        # $READTHEDOCS_OUTPUT: the place where we deploy the documentation
        - mkdir -p $READTHEDOCS_OUTPUT/html/ja
        - mkdir -p $READTHEDOCS_OUTPUT/html/en
        - cp -r docs/index.html $READTHEDOCS_OUTPUT/html/
        - cp -r docs/ja/_build/html/* $READTHEDOCS_OUTPUT/html/ja/
        - cp -r docs/en/_build/html/* $READTHEDOCS_OUTPUT/html/en/
