###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
add_module_names = False
author = 'Jij Inc.'
autoapi_add_toctree_entry = True
autoapi_dirs = ['../qamomile']
autoapi_options = ['members', 'undoc-members', 'show-inheritance', 'show-module-summary', 'imported-members', 'no-index']
autoapi_python_class_content = 'both'
autoapi_type = 'python'
bibtex_bibfiles = ['references.bib']
bibtex_reference_style = 'author_year'
comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2023'
exclude_patterns = ['**.ipynb_checkpoints', '.DS_Store', 'Thumbs.db', '_build']
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book', 'sphinx_thebe', 'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_design', 'sphinx_book_theme', 'sphinx.ext.napoleon', 'autoapi.extension', 'sphinx.ext.autodoc', 'sphinxcontrib.bibtex', 'sphinx_jupyterbook_latex', 'sphinx_multitoc_numbering']
external_toc_exclude_missing = False
external_toc_path = '_toc.yml'
highlight_language = 'python'
html_baseurl = ''
html_favicon = ''
html_logo = 'qamomile_logo.png'
html_search_language = 'en'
html_sourcelink_suffix = ''
html_theme = 'sphinx_book_theme'
html_theme_options = {
    'code_font_family': 'monospace', 
    'code_font_size': '0.9em',
    'launch_buttons': {
        'notebook_interface': 'classic',
        'colab_url': 'https://colab.research.google.com'
    }
}
html_title = 'Qamomile Documentation'
language = 'en'
latex_engine = 'pdflatex'
mathjax_path = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'
myst_enable_extensions = ['colon_fence', 'dollarmath', 'linkify']
myst_url_schemes = ['mailto', 'http', 'https']
nb_execution_allow_errors = False
nb_execution_cache_path = ''
nb_execution_excludepatterns = []
nb_execution_in_temp = False
nb_execution_mode = 'off'
nb_execution_timeout = 30
nb_output_stderr = 'show'
numfig = True
pygments_style = 'sphinx'
suppress_warnings = ['etoc.toctree']
use_jupyterbook_latex = True
use_multitoc_numbering = True
