name: Deploy Jupyter Book to GitHub Pages

on:
  push:
    branches:
      - main  # メインブランチにプッシュされたときに実行

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install --all-extras
        pip install -U jupyter-book

    - name: Build the book
      run: |
        cd docs
        jupyter-book build .

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html