name: Deploy Jupyter Book to GitHub Pages

on:
  push:
    # !!! "test/actions_jupyter-book-publish" is temporarilily added for testing purposes. !!!
    branches: ["main", "test/actions_jupyter-book-publish"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

# Build the landing page and jupyter book, integrate those pages and deploy those pages to GitHub Pages separately.
jobs: 
  build-lp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'docs/qamomile-lp/package-lock.json'
      # - name: Build Landing Page
      #   run: |
      #     cd docs/qamomile-lp
      - name: Build the LP
        run: |
          cd docs/qamomile-lp
          npm ci
          npm run build
          mkdir -p ../_build/html
          cp dist/index.html ../_build/html/landing.html
          cp ../index.html ../_build/html/index.html
          cp dist/*.png ../_build/html/
          cd ../..
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: doc-landing-page
          path: 'docs/_build/html'
  
  build-jupyter-book:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lang: [en, ja]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --all-extras
          poetry run pip install -U jupyter-book
      - name: Build the book and LP
        run: |
          cd docs
          poetry run jupyter-book build ${{ matrix.lang }}
          cd ..
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: doc-jupyter-book-${{ matrix.lang }}
          path: 'docs/${{ matrix.lang }}/_build/html'
  
  integrate-pages:
    needs: [build-lp, build-jupyter-book]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      - name: Create unified site structure
        run: |
          mkdir -p docs/_build/html
          cp -r doc-landing-page/* docs/_build/html
          mkdir -p docs/_build/html/en && cp -r doc-jupyter-book-en/* docs/_build/html/en/
          mkdir -p docs/_build/html/ja && cp -r doc-jupyter-book-ja/* docs/_build/html/ja/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: doc-jupyter-book
          path: 'docs/_build/html'

  # deploy:
  #   needs: [build-lp, build-jupyter-book, integrate-pages]
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download all artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: doc-jupyter-book
  #         path: .
  #     - name: Upload artifact
  #       uses: actions/upload-pages-artifact@v3
  #       with:
  #         name: doc-jupyter-book
  #         path: "."
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v4
